### PR TITLE
test(server): isolate entrypoint runtime environment

### LINKED ISSUE #9383: server-rest shard: isolate order-dependent initialization registry mock leak
## Observed failure

PR #9262's full `server-rest` shard failed on attempt 1 even though the PR changes only dependency bounds and keeps the locked websockets version unchanged.

- Workflow: <https://github.com/synaptent/aragora/actions/runs/29555676000>
- Failed job: <https://github.com/synaptent/aragora/actions/runs/29555676000/job/87808966588>
- Seed: `1637355963`
- Failure: `tests/server/test_initialization_root.py::TestInitializeSubsystemsAsync::test_initializes_and_logs_async`
- Error: `AttributeError: Mock object has no attribute 'elo_system'`
- Attempt 1 result: 1 failed, 10,039 passed, 3 skipped.

The exact test passed independently on both PR head `d21e78bd1371b2fa4080f24e9dba3ce694b08547` and exact base `6d6ccb7e592d215cce5cd726ce890ee5903c9ae1` with the same random seed. A single failed-job rerun then passed the entire shard and workflow on attempt 2. This points to order-dependent shared mock/module state rather than #9262 behavior.

## Acceptance criteria

- [ ] Reproduce or narrow the polluting predecessor under xdist/loadscope and seed `1637355963`; if nondeterministic, add a bounded stress reproducer.
- [ ] Ensure the registry object used by `initialize_subsystems_async` cannot inherit a strict mock lacking the `elo_system` field from another test.
- [ ] Add a regression test that runs the suspected polluter and `test_initializes_and_logs_async` in the failing order.
- [ ] Verify the relevant `server-rest` slice repeatedly without relying on a workflow rerun as proof.
- [ ] Preserve fixture isolation; do not weaken the assertion or replace the strict mock with an unconstrained mock merely to hide the leak.

## Impact

The flake turns a green, evidence-complete Tier 1 PR into `mergeStateStatus=UNSTABLE` and consumes roughly 10 minutes for a 10,000-test shard rerun, delaying settlement even though required checks are green.

### PR DESCRIPTION
**Pull request by scarmani**
## Summary
- restore all runtime variables mutated by server entrypoint tests after each test
- prevent `ARAGORA_DEMO_MODE=true` from leaking into later worker-local initialization tests
- keep the fix scoped to the polluting test module

## Root cause
`test_explicit_handler_tiers_are_not_overwritten` exercised the offline defaults while monkeypatching only `ARAGORA_HANDLER_TIERS`. `_configure_runtime_environment` also set `ARAGORA_DEMO_MODE`, so that untracked value survived fixture teardown and activated demo seeding in a later class-spec mock.

## Validation
- polluter then victim: 2 passed
- victim then polluter: 2 passed
- `tests/server/test_server_entrypoint.py tests/server/test_initialization_root.py`: 48 passed
- ruff check and format check: passed
- automation PR preflight: passed
- `make ci-required`: ruff passed; stopped at the existing repository-wide mypy baseline (1,983 errors in 537 production files)

Fixes #9383

### CODE REVIEW

**Comment by scarmani** [comment]
## Claude independent model review

Reviewer: claude (anthropic) — independent adversarial model review via the Aragora Claude reviewer, grounded on the exact PR head.
Head: b222118 (b222118d663b49378fa9488681f21d4bff41c27b), committed 2026-07-17T06:04:16Z.
PR: #9384.
Model family: claude

Verdict: PASS

- [P3] tests/server/test_server_entrypoint.py:14 — `_RUNTIME_ENV_KEYS` is a hardcoded mirror of the `setdefault` keys in `_configure_runtime_environment` (aragora/server/__main__.py:85-91). It is complete at head b222118, but if the entrypoint later gains another default (e.g. a new `ARAGORA_*` key), this list silently drifts and the leak returns. Consider deriving the list or snapshotting/restoring env keys by `ARAGORA_` prefix. Non-blocking.

Verification notes: the fixture's pop-then-`update(original)` teardown correctly restores both previously-set and previously-absent keys; its interaction with `monkeypatch` is order-safe (both restore paths converge to the pre-test environment regardless of teardown ordering, since autouse setup captures `original` before the test body mutates anything). All 4 tests in the file pass locally (0.98s).

dogfood: yes

**Comment by scarmani** [comment]
## OpenAI independent model review

Reviewer: openai (openai) — independent adversarial model review via Codex CLI OpenAI harness, grounded on the exact PR head.
Head: b222118 (b222118d663b49378fa9488681f21d4bff41c27b), committed 2026-07-17T06:04:16Z.
PR: #9384.
Model family: openai

Verdict: PASS

No findings.

dogfood: yes
