### PR TITLE
ci(pollution-guard): slice randomized guard + persist failing seed/nodes [Tier-4] (#9239)

### PR DESCRIPTION
**Pull request by an0mium**
Refs #9239 (M-TRUST: restore test trustworthiness) — **Tier-4 workflow change**, human approval required.

## Problem
The `test-pollution-randomized` job (\`.github/workflows/test.yml\` ~L1171) has three defects called out by #9239:

1. \`needs: test-fast\` couples the guard to the fast PR lane — a red fast lane silently skips the guard.
2. One giant \`pytest\` command over 13 test directories, run twice with different seeds, regularly hits the 20-minute cap.
3. Failing seed + node IDs live only in the raw log — nothing persistable for bisection or trend tracking.

## Change
Split the job into **bounded domain slices** with **one fixed + one rotating seed** per slice, and **persist failing node IDs as artifacts**:

- Slices:
  - \`core\` → \`tests/debate tests/knowledge tests/agents tests/memory\` (fixed seed 12345)
  - \`server\` → \`tests/server/handlers tests/control_plane tests/rbac tests/events tests/observability\` (fixed seed 54321)
  - \`workflow\` → \`tests/workflow tests/compliance tests/gauntlet tests/cli\` (fixed seed 99999)
- Rotating seed: \`github.run_number % 100000\` (same across slices per run for cross-slice correlation).
- Both runs write \`--junitxml\` → an inline Python step distills failing testcases into \`artifacts/pollution-guard/failing_nodes.json\` (fields: \`slice\`, \`kind\`, \`seed\`, \`node_id\`).
- Artifact \`pollution-guard-<slice>-<run>\` uploaded on \`if: always()\` with 14-day retention.
- Removed \`needs: test-fast\` — the guard now runs on push/schedule regardless of PR shard state.
- Still \`if: github.event_name != 'pull_request'\`; **not** a PR admission gate.
- Aggregation step fails the slice job iff either seed run failed, but only after the artifact is uploaded — so operators can bisect from the JSON without rerunning CI.

## Constraints preserved
- Same test-marker exclusions (\`not slow and not load and not e2e ...\`).
- Same 60s per-test timeout.
- Same 20-minute job wall-clock cap (per slice, not per giant command).
- No new required checks.

## Diff size
- 1 file (\`.github/workflows/test.yml\`), +126/-21.

## Follow-up (separate Tier-4 PRs)
- Nightly-core signal (acceptance criterion 3 of #9239).
- Bisection tooling on \`failing_nodes.json\` — tracks with #9122.

## Tier
- **Tier 4** — CI workflow change. Human approval required; draft until reviewed.

### CODE REVIEW

**Comment by scarmani** [comment]
## Claude independent model review

Reviewer: claude (anthropic) — independent adversarial model review via the Aragora Claude reviewer, grounded on the exact PR head.
Head: c6ed83f (c6ed83ffdcd30b857848fa7eb50c01439cdd219c), committed 2026-07-12T02:14:56Z.
PR: #9245.
Model family: claude

Verdict: CHANGES-REQUESTED

- **[P2]** `.github/workflows/test.yml` — "Extract failing node IDs" step: the node-ID reconstruction `f"{classname.replace('.', '/')}.py::{testname}"` is wrong for class-based tests. For `tests/foo/test_mod.py::TestBar::test_x`, pytest's JUnit classname is `tests.foo.test_mod.TestBar`, so the script emits the invalid ID `tests/foo/test_mod/TestBar.py::test_x`. Class-based tests are pervasive in this repo (handler suites especially), so `failing_nodes.json` — the PR's stated bisection artifact — will be unusable for a large fraction of real failures. Note xunit2 JUnit output has no `file` attribute to fall back on; the reconstruction needs to distinguish module vs. class segments (or capture node IDs directly, e.g. via a `pytest` report hook/`-rf` parse) rather than a blind dot→slash replace. The in-code comment asserting classname is "file path with dots" is itself incorrect for this case.
- **[P3]** `.github/workflows/test.yml` — upload step: artifact name `pollution-guard-${{ matrix.slice }}-${{ github.run_number }}` collides on job re-runs (`upload-artifact@v4` rejects duplicate names across attempts of the same run), and the upload step has no `continue-on-error`, so re-running a green slice can fail purely on the 409. Append `${{ github.run_attempt }}` (or set `overwrite: true`).
- **[P3]** `.github/workflows/test.yml` — slicing is a deliberate but real coverage regression: cross-domain pollution (e.g. `tests/debate` state leaking into `tests/workflow`) is now structurally undetectable since slices run in separate pytest processes, and per-directory seed coverage drops from 4 effective seeds (3 fixed + shared dynamic) to 2. Worth stating in the job comment that cross-slice pollution is out of scope so a future green guard isn't over-trusted.
- **[P3]** `.github/workflows/test.yml` — `continue-on-error: true` on the two pytest steps is dead config: the scripts `set +e` and unconditionally `exit 0`, so the steps can't fail. Harmless, but drop one mechanism to avoid implying the other is load-bearing.

dogfood: yes

**Comment by scarmani** [comment]
## OpenAI independent model review

Reviewer: openai (openai) — independent adversarial model review via Codex CLI OpenAI harness, grounded on the exact PR head.
Head: c6ed83f (c6ed83ffdcd30b857848fa7eb50c01439cdd219c), committed 2026-07-12T02:14:56Z.
PR: #9245.
Model family: openai

Verdict: CHANGES-REQUESTED

- [P2] `.github/workflows/test.yml` / `Extract failing node IDs from JUnit XML`: the JUnit parser reconstructs pytest node IDs incorrectly for class-based tests. A classname like `tests.foo.test_bar.TestCase` becomes `tests/foo/test_bar/TestCase.py::test_method`, but the runnable node ID is `tests/foo/test_bar.py::TestCase::test_method`. The uploaded “failing node IDs” artifact will be misleading for common pytest classes, undermining the new bisect/debug workflow.

dogfood: yes

**Comment by scarmani** [comment]
## Claude independent model review

Reviewer: claude (anthropic) — independent adversarial model review via the Aragora Claude reviewer, grounded on the exact PR head.
Head: ee9c7ef (ee9c7ef82e4f98d9ffcdae90bdbf9186500a4540), committed 2026-07-13T21:24:35Z.
PR: #9245.
Model family: claude

Verdict: PASS

- [P3] `.github/workflows/test.yml` (extract step, `failing_nodes.json`): if pytest dies before/while writing the JUnit XML (collection crash, hard kill at the job's 20-min cap), the XML is missing or truncated and the script silently `continue`s — the job still fails closed on `rc`, but the `::error` message claims failing node IDs were uploaded when `failing_nodes.json` can be empty. Downstream bisect lanes should treat an empty summary as "rerun needed," or the message should be conditional.
- [P3] `.github/workflows/test.yml` (node-id reconstruction): when no `classname` prefix matches an existing module file, the fallback is exactly the blind `dot->slash` replacement the adjacent comment calls invalid for class-based tests, so the artifact can contain non-runnable node IDs. Harmless to the gate, but worth flagging entries where no prefix matched (e.g. a `resolved: false` field).
- [P3] Sensitivity reduction vs. the old guard: per-path seed coverage drops from ~4 orders per run to 2, and cross-directory pollution (e.g. `tests/debate` → `tests/cli`) is structurally undetectable now. This is documented in the SCOPE NOTE and acceptable for a stress guard, but note the referenced "full matrix / nightly lanes" backstop must actually exist for the claim to hold.
- [P3] Slice sizing is unvalidated against the unchanged 20-minute cap: the `server` slice (`tests/server/handlers` alone is the largest test surface in the repo) runs twice per job with `-x` removed, so a badly polluted run with many 60s-timeout hangs could still hit the job cap — which kills the run mid-step and makes the artifact-upload guarantee best-effort. Consider a per-step `timeout-minutes` below the job cap so the extract/upload steps always get their window.
- [P3] Minor dead code: `steps.fixed-seed-run.outputs.seed` is written but never consumed; and the rotating seed can collide with a slice's fixed seed (`run_number % 100000 == fixed_seed`), silently halving that run's order coverage.

Mechanically the change is sound: all 13 original test paths are preserved across the three slices, both pytest steps capture `rc` under `set +e` and the final gate fails on any non-zero or empty `rc` (fail-closed, including the skipped/errored-step case), matrix values interpolated into `run:` are workflow-defined literals with no untrusted input (the job never runs on `pull_request`), and the quoted heredoc keeps the Python block free of expression injection.

dogfood: yes

**Comment by scarmani** [comment]
## OpenAI independent model review

Reviewer: openai (openai) — independent adversarial model review via Codex CLI OpenAI harness, grounded on the exact PR head.
Head: ee9c7ef (ee9c7ef82e4f98d9ffcdae90bdbf9186500a4540), committed 2026-07-13T21:24:35Z.
PR: #9245.
Model family: openai

Verdict: PASS

No findings.

dogfood: yes

**Comment by scarmani** [comment]
Tier-4 Human Settlement Authorization

PR: #9245
Exact head: ee9c7ef82e4f98d9ffcdae90bdbf9186500a4540
Authorized action: admin_squash_merge and branch_protection_reconcile, only if #9245 is non-draft and live exact-head checks/merge-packet remain otherwise green.

Human-risk settlement: I accept the Tier 4 risk for this PR.

**Comment by scarmani** [comment]
#9245 exact-head settlement hold

Head remains `ee9c7ef82e4f98d9ffcdae90bdbf9186500a4540`. All six required checks and exact-head Claude/OpenAI quorum are green, but GitHub correctly remains `UNSTABLE` because two non-required `test-fast` shards produced real failures:

- `server-rest`: `tests/server/test_initialization_root.py::TestInitializeSubsystemsAsync::test_initializes_and_logs_async` failed with `AttributeError: Mock object has no attribute 'elo_system'` after 10,026 passes.
- `storage`: `tests/storage/test_store_extended.py::TestPatternPruningExtended::test_prune_patterns_archive_created` failed because `total_archived == 0` after 7,825 passes.
- `debate-am` was cancelled near 99% after the other shard failures.

Focused detached-worktree reproduction was run at both exact PR head and current main `a1cb413d7e4bba0a2944b8218d23587e3bede462`. Both tests passed individually at both heads (4/4 focused invocations green), and the test files plus `aragora/server/initialization.py` are unchanged between the PR and current main. This isolates the blocker as order/xdist-sensitive test instability rather than a deterministic workflow-source regression.

No CI rerun, settlement, merge, workflow edit, or branch update was performed. The existing Tier-4 authorization is not being used while the live gate is `UNSTABLE`.

**Comment by scarmani** [comment]
Tier-4 Human Settlement Authorization

PR: #9245
Exact head: ee9c7ef82e4f98d9ffcdae90bdbf9186500a4540
Authorized action: admin_squash_merge and branch_protection_reconcile, only if #9245 is non-draft and live exact-head checks/merge-packet remain otherwise green.

Human-risk settlement: I accept the Tier 4 risk for this PR.
