### PR TITLE
test: tolerate FastAPI included router wrapper in swarm-status route check

### PR DESCRIPTION
**Pull request by an0mium**
## Summary
Salvages stranded commit `6f4a72226d` (2026-06-25, never merged). FastAPI 0.138+ wraps included routers, making direct `app.routes` path inspection version- and import-order-dependent — the exact `'_IncludedRouter' object has no attribute 'path'` failure that blocks the server-rest shard on #9073, #8809, and #9064 while the test passes in isolation. The test now asserts the supported `url_path_for` lookup contract.

Test-only, three assertions swapped; the server shard stays enforcing (per the cross-validated remedy: fix the brittle assertion, don't make "passes alone" equivalent to success).

#### Test plan
- [x] tests/server/fastapi/routes/test_swarm_status.py green (17 tests)
- [x] ruff check/format clean; automation preflight ok

Generated with [Devin](https://devin.ai)

### CODE REVIEW

**Comment by an0mium** [comment]
## OpenAI independent model review

Reviewer: openai (openai) — independent adversarial model review via Codex CLI OpenAI harness, grounded on the exact PR head.
Head: 11e7071 (11e70715fda515c3b955837b72f72a5986441ead), committed 2026-07-10T17:41:46Z.
PR: #9182.
Model family: openai

Verdict: PASS

No findings.

dogfood: yes

**Comment by an0mium** [comment]
Evidence posted (openai PASS, counting). Shard status, honestly: this PR's IncludedRouter fix works — test_swarm_status no longer fails in-shard — but the server-rest shard now surfaces a SECOND pollution victim: tests/server/test_initialization_root.py::test_initializes_and_logs_async fails in-shard with "Mock object has no attribute 'elo_system'" yet passes in isolation (44/44 green). The test uses MagicMock(spec=SubsystemRegistry), so a shard-mate is polluting module identity (patched/reloaded SubsystemRegistry changing the spec surface). That's a distinct polluter needing its own hunt — out of this PR's test-only scope. Rerunning the shard (xdist distribution varies); if it stays red, the pollution hunt is the follow-up, not a revert of this fix.
