### ISSUE TITLE
server-rest shard: isolate order-dependent initialization registry mock leak

### ISSUE THREAD

**Issue by scarmani** [an0mium/aragora#9383]
## Observed failure

PR #9262's full `server-rest` shard failed on attempt 1 even though the PR changes only dependency bounds and keeps the locked websockets version unchanged.

- Workflow: <https://github.com/synaptent/aragora/actions/runs/29555676000>
- Failed job: <https://github.com/synaptent/aragora/actions/runs/29555676000/job/87808966588>
- Seed: `1637355963`
- Failure: `tests/server/test_initialization_root.py::TestInitializeSubsystemsAsync::test_initializes_and_logs_async`
- Error: `AttributeError: Mock object has no attribute 'elo_system'`
- Attempt 1 result: 1 failed, 10,039 passed, 3 skipped.

The exact test passed independently on both PR head `d21e78bd1371b2fa4080f24e9dba3ce694b08547` and exact base `6d6ccb7e592d215cce5cd726ce890ee5903c9ae1` with the same random seed. A single failed-job rerun then passed the entire shard and workflow on attempt 2. This points to order-dependent shared mock/module state rather than #9262 behavior.

## Acceptance criteria

- [ ] Reproduce or narrow the polluting predecessor under xdist/loadscope and seed `1637355963`; if nondeterministic, add a bounded stress reproducer.
- [ ] Ensure the registry object used by `initialize_subsystems_async` cannot inherit a strict mock lacking the `elo_system` field from another test.
- [ ] Add a regression test that runs the suspected polluter and `test_initializes_and_logs_async` in the failing order.
- [ ] Verify the relevant `server-rest` slice repeatedly without relying on a workflow rerun as proof.
- [ ] Preserve fixture isolation; do not weaken the assertion or replace the strict mock with an unconstrained mock merely to hide the leak.

## Impact

The flake turns a green, evidence-complete Tier 1 PR into `mergeStateStatus=UNSTABLE` and consumes roughly 10 minutes for a 10,000-test shard rerun, delaying settlement even though required checks are green.
